"""ORM model for a TopicWord generated by BERTopic in the system"""

from sqlalchemy import Column, Integer, String, Float, ForeignKey, Index, Boolean
from sqlalchemy.orm import relationship, deferred
from sqlalchemy_utils import TSVectorType

from app.db.base_class import Base

class TopicWord(Base):
    """ORM model for a TopicWord"""
    
    __table_name__ = "topicword"

    id = Column(Integer, primary_key=True, index=True)
    word = Column(String, nullable=False)
    frequency = Column(Float, nullable=False)
    fk_topic_model = Column(Integer, ForeignKey("topicmodel.id"))