"""add audio_file_key and peaks_file_key to document model

Revision ID: 3961bb002586
Revises: f125a8d42852
Create Date: 2021-09-17 09:16:18.829890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3961bb002586'
down_revision = 'f125a8d42852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('audio_file_key', sa.String(), nullable=True))
    op.add_column('document', sa.Column('peaks_file_key', sa.String(), nullable=True))
    op.drop_column('document', 'filename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('document', 'peaks_file_key')
    op.drop_column('document', 'audio_file_key')
    # ### end Alembic commands ###
