"""rename transcription table to aws_transcription

Revision ID: 4cc7640f8952
Revises: 130b136ff1b0
Create Date: 2021-10-29 10:35:43.373554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4cc7640f8952'
down_revision = '130b136ff1b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcription_id'), 'transcription', ['id'], unique=False)
    op.drop_index('ix_aws_transcription_id', table_name='aws_transcription')
    op.drop_table('aws_transcription')
    op.drop_constraint('document_fk_aws_transcription_fkey', 'document', type_='foreignkey')
    op.create_foreign_key(None, 'document', 'transcription', ['fk_aws_transcription'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.create_foreign_key('document_fk_aws_transcription_fkey', 'document', 'aws_transcription', ['fk_aws_transcription'], ['id'])
    op.create_table('aws_transcription',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('raw', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('full_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='aws_transcription_pkey')
    )
    op.create_index('ix_aws_transcription_id', 'aws_transcription', ['id'], unique=False)
    op.drop_index(op.f('ix_transcription_id'), table_name='transcription')
    op.drop_table('transcription')
    # ### end Alembic commands ###
