"""Add task_id to document ORM

Revision ID: 98bfbbda32b0
Revises: 384ac8c09198
Create Date: 2022-02-15 13:55:46.197279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98bfbbda32b0'
down_revision = '384ac8c09198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('task_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'task_id')
    # ### end Alembic commands ###
