"""make initial order of word table nullable

Revision ID: c73cf9ddb1a6
Revises: f1665588a28c
Create Date: 2021-12-22 13:58:23.222336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c73cf9ddb1a6'
down_revision = 'f1665588a28c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('word', 'initial_order',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('word', 'initial_order',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
