"""extend word model for editable transcripts

Revision ID: f1665588a28c
Revises: b168956d7668
Create Date: 2021-11-05 11:37:55.203011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1665588a28c'
down_revision = 'b168956d7668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('edited', sa.Boolean(), nullable=True))
    op.add_column('word', sa.Column('current_order', sa.Integer(), nullable=True))
    op.add_column('word', sa.Column('edit_version_no', sa.Integer(), nullable=True))
    op.add_column('word', sa.Column('edited', sa.Boolean(), nullable=True))
    op.alter_column('word', 'order', nullable=False, new_column_name='initial_order')
    
    op.execute("UPDATE word SET current_order = initial_order")

    op.execute("UPDATE document SET edited = false")
    op.alter_column('document', 'edited', nullable=False)

    op.execute("UPDATE word SET edited = false")
    op.alter_column('word', 'edited', nullable=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('word', 'initial_order', nullable=False, new_column_name='order')
    op.drop_column('word', 'edited')
    op.drop_column('word', 'edit_version_no')
    op.drop_column('word', 'current_order')
    op.drop_column('document', 'edited')
    # ### end Alembic commands ###
