[tool.poetry]
name = "joureka"
version = "0.1.0"
description = ""
authors = ["Felix Mertineit <fmertineit@gmail.com>", "Jonas Schweiger <jonas.schweiger@gmx.de>"]

[tool.poetry.dependencies]
python = ">=3.8, <3.10"
uvicorn = "^0.11.3"
fastapi = "^0.65.1"
python-multipart = "^0.0.5"
email-validator = "^1.0.5"
requests = "^2.23.0"
celery = "^4.4.2"
passlib = {extras = ["bcrypt"], version = "^1.7.2"}
tenacity = "^6.1.0"
pydantic = "^1.4"
emails = "^0.5.15"
raven = "^6.10.0"
gunicorn = "^20.0.4"
jinja2 = "^2.11.2"
psycopg2-binary = "^2.8.5"
alembic = "^1.4.2"
sqlalchemy = ">=1.3.16, < 1.4"
python-jose = {extras = ["cryptography"], version = "^3.1.0"}
aiofiles = "^0.6.0"
boto3 = "^1.16.18"
SQLAlchemy-Utils = "^0.36.8"
temppathlib = "^1.1.0"
asrecognition = "^0.0.4"
vosk = "^0.3.32"
spacy = "^3.1.4"
jouresearch-nlp = {git = "https://github.com/joureka-ai/jouresearch-nlp", rev = "main"}
#jouresearch-nlp = {file = "/home/fmert/repo/joureka/jouresearch-nlp/dist/jouresearch_nlp-0.1.3-py3-none-any.whl"}
regex = "^2021.11.10"


[tool.poetry.dev-dependencies]
mypy = "^0.770"
black = "^19.10b0"
isort = "^4.3.21"
autoflake = "^1.3.1"
flake8 = "^3.7.9"
pytest = "^6.0.0"
sqlalchemy-stubs = "^0.3"
pytest-cov = "^2.8.1"
pylint = "^2.6.0"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 88

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
